### ISSUE TITLE
CI build not running Template.NEP5.UnitTests

### ISSUE THREAD

**Issue by devhawk** [neo-project/neo-devpack-dotnet#366]
main.yml includes the following:

``` yaml
- name: Test Neo.Compiler.MSIL.UnitTests
  run: dotnet test tests/Neo.Compiler.MSIL.UnitTests /p:CollectCoverage=true /p:CoverletOutput=${GITHUB_WORKSPACE}/coverage/ /p:Exclude=\"[Neo.SmartContract.*]*,[Neo.Compiler.MSIL.UnitTests]*,[Neo.Compiler.MSIL.UnitTests.*]*\"
- name: Test Neo.SmartContract.Framework.UnitTests
  run: dotnet test tests/Neo.SmartContract.Framework.UnitTests /p:CollectCoverage=true /p:CoverletOutput=${GITHUB_WORKSPACE}/coverage/lcov /p:MergeWith=${GITHUB_WORKSPACE}/coverage/coverage.json /p:Exclude=\"[Neo.SmartContract.*]*,[Neo.Compiler.MSIL.UnitTests]*,[Neo.Compiler.MSIL.UnitTests.*]*\" /p:CoverletOutputFormat=lcov
```

Should there also be a dotnet test run for tests/Template.NEP5.UnitTests?
